# Generated by Django 3.1.6 on 2021-02-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210202_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='won_bid',
            field=models.CharField(default='admin', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='users', to='auctions.Listing'),
        ),
    ]
